name: Generate Contribution Graph

on:
  schedule:
    - cron: '42 12 * * *'

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate contribution graph
        uses: Platane/snk@v3
        with:
          # GitHub user name to read the contribution graph from
          # Using the GitHub context variable `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}

          # List of files to generate, one per line
          # Each output can be customized with options as query string
          # Supported options:
          # - palette: A preset of color, one of [github, github-dark, github-light]
          # - color_snake: Color of the snake
          # - color_dots: Comma-separated list of dot colors
          #                The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                Exactly 5 colors are expected.
          files: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "swautele@student.s19.be"
          git add .
          git commit -m "Updated contribution graph"
          git push
