name: snake

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"

  # run on every push on the master branch
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: aelassas/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Commit and push changes
        run: |
          git config --global --add --bool push.autoSetupRemote true
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "swautele@student.s19.be"
          git add .
          git commit -m "Updated contribution graph"
          git push https://@github.com/swautelet/swautelet
